# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 146)
        Form.setMinimumSize(QtCore.QSize(400, 146))
        Form.setMaximumSize(QtCore.QSize(400, 146))
        self.heu = QtWidgets.QLCDNumber(Form)
        self.heu.setGeometry(QtCore.QRect(60, 60, 71, 61))
        self.heu.setStyleSheet("font-size:20pt")
        self.heu.setObjectName("heu")
        self.min = QtWidgets.QLCDNumber(Form)
        self.min.setGeometry(QtCore.QRect(150, 60, 71, 61))
        self.min.setStyleSheet("font-size:20pt")
        self.min.setObjectName("min")
        self.sec = QtWidgets.QLCDNumber(Form)
        self.sec.setGeometry(QtCore.QRect(250, 60, 71, 61))
        self.sec.setStyleSheet("font-size:20pt")
        self.sec.setObjectName("sec")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(120, 10, 161, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(130, 70, 21, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(230, 70, 21, 31))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600;\">Time Now</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600;\">:</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600;\">:</span></p></body></html>"))

    